version: '2'
services:
  servidor:
    build:
      context: ./servidor/
    command: /usr/app/node_modules/.bin/nodemon src/index.js
    volumes:
      - ./servidor/:/usr/app
      - /usr/app/node_modules
    ports:
      - "8080:8080"
      
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  cliente:
    build:
      context: ./cliente/
    command: npm start
    volumes:
      - ./cliente/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - servidor
    ports:
      - "3000:3000"
